// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObject.Models
{
    public partial class Attendance
    {
        public string Id { get; set; }
        public string StudentId { get; set; }
        public string SectionId { get; set; }
        public string Status { get; set; }

        public virtual Section Section { get; set; }
        public virtual Student Student { get; set; }
    }
}