// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObject.Models
{
    public partial class Course
    {
        public Course()
        {
            Enrollment = new HashSet<Enrollment>();
            Section = new HashSet<Section>();
        }

        public string Id { get; set; }
        public string Name { get; set; }
        public string SubjectId { get; set; }
        public string SemeterId { get; set; }
        public string InstructorId { get; set; }
        public DateTime? Shedule { get; set; }
        public int? Room { get; set; }
        public string Decription { get; set; }

        public virtual Instructor Instructor { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual ICollection<Enrollment> Enrollment { get; set; }
        public virtual ICollection<Section> Section { get; set; }
    }
}