// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObject.Models
{
    public partial class Instructor
    {
        public Instructor()
        {
            Course = new HashSet<Course>();
            Section = new HashSet<Section>();
        }

        public string Id { get; set; }
        public string Name { get; set; }
        public string Decription { get; set; }

        public virtual ICollection<Course> Course { get; set; }
        public virtual ICollection<Section> Section { get; set; }
    }
}