// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObject.Models
{
    public partial class Major
    {
        public Major()
        {
            Semeter = new HashSet<Semeter>();
            Student = new HashSet<Student>();
            Subject = new HashSet<Subject>();
        }

        public string Id { get; set; }
        public string Name { get; set; }
        public string Decription { get; set; }

        public virtual ICollection<Semeter> Semeter { get; set; }
        public virtual ICollection<Student> Student { get; set; }
        public virtual ICollection<Subject> Subject { get; set; }
    }
}