// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObject.Models
{
    public partial class Section
    {
        public Section()
        {
            Attendance = new HashSet<Attendance>();
        }

        public string Id { get; set; }
        public string Name { get; set; }
        public string CourseId { get; set; }
        public string InstructorId { get; set; }
        public string AttendanceId { get; set; }

        public virtual Course Course { get; set; }
        public virtual Instructor Instructor { get; set; }
        public virtual ICollection<Attendance> Attendance { get; set; }
    }
}